<a href="https://colab.research.google.com/github/MariuszGaw/datascience/blob/main/02_numpy_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
v1 = np.array([-1,4])

In [3]:
v1

array([0, 4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

In [7]:
v2 = np.array ([-10,10,13])

In [9]:
np.linalg.norm(v2)

19.209372712298546

In [11]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

In [12]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

**Mnożenie macierzy**

In [13]:
import numpy as np
X = np.array ([[2, -1, 3],
               [3,  1, 0]])
Y = np. array ([[2, 1, -1],
               [0, -1, 2],
               [3,2, 0]])
print(X,'\n','\n', Y)

[[ 2 -1  3]
 [ 3  1  0]] 
 
 [[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [14]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

**Wyznaczniki**

In [19]:
A = np.array([[2,4],[-1,3]])
print(A)

[[ 2  4]
 [-1  3]]


In [21]:
np.linalg.det(A)
round(np.linalg.det(A))

10

Ślad macierzy = suma po przekątnej

In [22]:
np.trace(A)

5

Macierz jednostkowa

In [23]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Macierz odwrotna

In [25]:
print(A)

[[ 2  4]
 [-1  3]]


In [26]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [29]:
C = np.dot(A,B)
C

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [35]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)
print(C)

[[1. 0.]
 [0. 1.]]


In [36]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

**Transponowanie**

In [37]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [38]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [39]:
A

array([[ 2,  4],
       [-1,  3]])

**Rozwiązywanie układ równań**

In [40]:
A = np.array([[2,4],[1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [42]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [49]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B
          )
print(X)

[[1.]
 [2.]]


In [53]:
X.shape

(2, 1)

**Funkcje statystyczne**

In [ ]:
price.sum()
# wszystkie elementy

price.sum(axis=0) # po kolumnach
price.sum(axis=1) # po wierszach
np.sum(price) # bezpośrednio z bilioteki numpy
np.min(price) # minimum z całej tablicy
np.min(price, axis=0) # z konkrentej kolumny
median () # niedozwolone
np.median(price) # mediana
np.mean(price, axis = 0) # średnia
np.std(price, axis = 0) # odchylenie standardowe
np.var(price, axis = 0) # wariancja