In [1]:
print('Hello Colab')

Hello Colab


In [3]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [5]:
np.__version__

'1.21.6'

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [8]:
x = np.array([1,3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndimx

AttributeError: ignored

In [12]:
x.ndim

1

In [13]:
x.shape

(2,)

In [14]:
x.size

2

In [15]:
x.dtype

dtype('int64')

In [16]:
x.shape

(2,)

In [18]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [19]:
x.dtype

dtype('float64')

In [21]:
x = np.array([[1,2],[-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [24]:
x.type

AttributeError: ignored

In [25]:
x.dtype

dtype('int64')

In [27]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [28]:
x,shape

NameError: ignored

In [29]:
x.shape

(2, 3)

In [30]:
x = np.array(
    [[[4,3,1],
    [3,1,2]],

    [[4,1,3],
     [4,2,1]]]
)
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [31]:
x.ndim

3

In [32]:
x.shape

(2, 2, 3)

In [8]:
import numpy as np
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [9]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
A

array([1., 2., 3.])

**Tworzenie tablic**

In [15]:
B = np.zeros(shape=(1000,1000), dtype='int')
B.size

1000000

In [16]:
B.dsize

AttributeError: ignored

In [19]:
np.ones(shape=(5,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [26]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [28]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [29]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [32]:
A = np.arange(15)

In [33]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [36]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [38]:
A.reshape((2,-1))

ValueError: ignored

**Podstawowe operacje na tablicach**

In [48]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [47]:
A/B

<ipython-input-47-5d618eb3152c>:1: RuntimeWarning: divide by zero encountered in true_divide
  A/B


array([ 1.        , -1.        ,  1.33333333,         inf])

In [40]:
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [41]:
print(A,B)

[3 1 4 2] [ 3 -1  3  2]


In [42]:
A+B

array([6, 0, 7, 4])

In [43]:
A - B

array([0, 2, 1, 0])

In [44]:
A*B

array([ 9, -1, 12,  4])

In [45]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [49]:
A+3

array([6, 4, 7, 5])

In [50]:
2*A

array([6, 2, 8, 4])

In [51]:
print(A)

[3 1 4 2]


In [53]:
A+3*B

array([12, -2, 13,  8])

In [54]:
np.add(A,B)

array([6, 0, 7, 4])

In [56]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [57]:
np.subtract(B,A)

array([ 0, -2, -1,  0])

In [59]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [61]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [67]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [68]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [69]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [70]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [72]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [63]:
X

array([[ 1,  3],
       [-2,  0]])

In [64]:
Y

array([[ 6,  0],
       [-1,  2]])

**Generowanie liczb pseudolosowych**

In [73]:
np.random.seed(0)

In [74]:
np.random.randn()

1.764052345967664

In [75]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [76]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [78]:
np.random.rand()

0.1965823616800535

In [80]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [82]:
np.random.randint(10)

3

In [85]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [90]:
np.random.choice([4,2,1,4,5])

1

In [91]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [96]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.random.shuffle(data)

od razu zachodzi zmiana

In [98]:
data

array([7, 2, 1, 6, 0, 5, 9, 3, 4, 8])

**Podstawowe funkcje**

In [1]:
np.exp(1)

NameError: ignored

In [2]:
import numpy as np

In [3]:
np.exp(1)

2.718281828459045

In [4]:
np.sqrt(9)

3.0

In [6]:
np.all([2,3,0])

False

In [8]:
np.any([0,0,0])

False

In [9]:
bool(0)

False

In [10]:
bool(1.5)

True

In [14]:
A = np.random.rand(5)
A

array([0.37952021, 0.15994852, 0.88944967, 0.90677733, 0.3604798 ])

In [15]:
np.argmax(A)

3

In [16]:
A[np.argmax(A)]

0.9067773282371802

In [17]:
np.argmin(A)

1

In [18]:
np.argsort(A)

array([1, 4, 0, 2, 3])

In [19]:
np.max(A)

0.9067773282371802

In [20]:
np.min(A)

0.15994851839746838

In [21]:
np.mean(A)

0.5392351061562151

In [22]:
np.median(A)

0.3795202051859501

In [23]:
np.std(A)

0.3030043405879985